# file: C:\Users\m_tes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\core\_exceptions.py
# hypothesis_version: 6.137.3

[1000, 1024, 'EiB', 'GiB', 'KiB', 'MiB', 'PiB', 'TiB', '_msg', 'axis', 'bytes', 'ndim', 'numpy', '{:#.0f} {}', '{:#.3g} {}', '{:.0f} {}', '{} ']