# file: C:\Users\m_tes\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\_pytest\_py\error.py
# hypothesis_version: 6.137.3

[267, 'P', 'R', 'UnknownErrnoNone', '[{}]: {}', '_', '__doc__', '__module__', 'errno', 'py.error', 'win32', '{}.{} {!r}: {} ']